name: "SunGather-AH"
version: "0.1.5"
slug: sungather-ah
description: "Extract Sungrow data from local Inverter"
arch: 
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: "https://github.com/caliph9k/SunGather-HomeAssistant"
startup: application
ingress: true
ingress_port: 8099
boot: auto
discovery:
  - "mqtt"
services:
  - "mqtt:need"
map:
  - share:rw
options:
  timeout: 10
  scan_interval: 30
  inverter:
    - host: 192.168.1.100
      connection: "http"
      smart_meter: True
      custom_mqtt_server: False
      log_console: "INFO"
      username: "user"
      password: "pw1111"
schema:
  timeout: int(3,60)
  scan_interval: int(5,600)
  inverter:
    - host: str
      connection: "list(sungrow|modbus|http)"
      smart_meter: bool
      custom_mqtt_server: bool
      log_console: "list(OFF|INFO|WARNING|ERROR|DEBUG)?"
      username: str
      password: password
panel_icon: mdi:SolarPowerVariant
init: false
